/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../00.JNI/jni.h"
/* Header for class CallJava */

#ifndef _Included_CallJava
#define _Included_CallJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallJava
 * Method:    changeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CallJava_changeName
  (JNIEnv *, jobject);

/*
 * Class:     CallJava
 * Method:    sayHiFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_CallJava_sayHiFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
