/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../00.JNI/jni.h"
/* Header for class CallC */

#ifndef _Included_CallC
#define _Included_CallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallC
 * Method:    getFullName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CallC_getFullName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     CallC
 * Method:    getFirstName
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CallC_getFirstName
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
