/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../00.JNI/jni.h"
/* Header for class java_HelloStringFromC */

#ifndef _Included_java_HelloStringFromC
#define _Included_java_HelloStringFromC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_HelloStringFromC
 * Method:    helloStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloStringFromC_helloStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
